// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.DataAccess.Migrations
{
    [DbContext(typeof(BookStore.DataAccess.BookStoreDbContext))]
    partial class BookStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("BookStore.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("FirstName", "LastName")
                        .IsUnique();
                    b.ToTable("Authors");
                });

            modelBuilder.Entity("BookStore.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");
                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<string>("Description")
                        .HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Isbn")
                        .IsUnique();
                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookStore.Models.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<string>("Location")
                        .HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Stores");
                });

            modelBuilder.Entity("BookStore.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");
                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");
                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<string>("Changes")
                        .HasColumnType("TEXT");
                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BookStore.Models.BookAuthor", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");
                    b.HasKey("BookId", "AuthorId");
                    b.HasIndex("AuthorId");
                    b.ToTable("BookAuthor");
                });

            modelBuilder.Entity("BookStore.Models.StoreBook", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT");
                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");
                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");
                    b.HasKey("StoreId", "BookId");
                    b.HasIndex("BookId");
                    b.ToTable("StoreBook");
                });

            modelBuilder.Entity("BookStore.Models.BookAuthor", b =>
                {
                    b.HasOne("BookStore.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("BookStore.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Models.StoreBook", b =>
                {
                    b.HasOne("BookStore.Models.Book", "Book")
                        .WithMany("StoreBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("BookStore.Models.Store", "Store")
                        .WithMany("StoreBooks")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
